# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Welcome
    init: |
      ./build.sh
      echo "Init executed at $(date)"
    command: echo "Hello executed at $(date)"

ports:
  - port: 3300
    onOpen: ignore
    visibility: public

  - port: 3306
    onOpen: ignore
    visibility: public

  - port: 5000
    onOpen: ignore
    visibility: public

  - port: 5005
    onOpen: ignore
    visibility: public

  - port: 4242
    onOpen: ignore
    visibility: public

  - port: 4243
    onOpen: ignore
    visibility: public

  - port: 4244
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode

