version: '2'

services:
  nginx:
    network_mode: host
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4242:4242