name: Deploy Blink on AWS

on:
  push: {}
  workflow_dispatch: {}

jobs:
  deploy-blink-to-aws:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: 'x64'
      
      - name: Checkout Blink
        uses: actions/checkout@v4
        with:
          repository: caravanacloud/blink

      - name: Build packages with Maven
        run: mvn --no-transfer-progress -B package
        continue-on-error: true        

      - name: Debug
        run: find .

