name: Build Blink

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build-blink:
    runs-on: ubuntu-latest
    env:
      QUARKUS_PROFILE: prod

    steps:
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'
      
      - name: Checkout Blink
        uses: actions/checkout@v4

      - name: Build packages with Maven
        run: mvn --no-transfer-progress -B package | tee mvn.log
        continue-on-error: true        

      - name: Upload maven log artifact
        uses: actions/upload-artifact@v2
        with:
          name: mvn.log
          path: mvn.log

