name: Publish Blink

on:
  push: 
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-blink:
    runs-on: ubuntu-latest
    env:
      QUARKUS_PROFILE: prod

    steps:
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'
      
      - name: Checkout Blink
        uses: actions/checkout@v4
        with:
          repository: caravanacloud/blink

      - name: Build packages with Maven
        run: mvn --no-transfer-progress -B -DskipTests package
        continue-on-error: true        

      - name: Create GitHub Release
        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Use your personal token to get more rate limits
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

