name: Publish Blink

on:
  push: 
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  publish-blink:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      QUARKUS_PROFILE: prod

    steps:
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'
      
      - name: Checkout Blink
        uses: actions/checkout@v4
        with:
          repository: caravanacloud/blink

      - name: Build packages with Maven
        run: mvn --no-transfer-progress -B -DskipTests package
        continue-on-error: true        

      # git tag v0.0.1 && git push origin --tags
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

        with:
          files: blink-core/target/blink-core.jar


