name: Publish Blink

on:
  create: {}
  workflow_dispatch: {}

jobs:
  build-blink:
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    env:
      QUARKUS_PROFILE: prod

    steps:
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'
      
      - name: Checkout Blink
        uses: actions/checkout@v4
        with:
          repository: caravanacloud/blink

      - name: Build packages with Maven
        run: mvn --no-transfer-progress -B package
        continue-on-error: true        

      - name: Debug
        run: find .

